version: "3.9"
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=flux
  nodered:
    image: "nodered/node-red"
    ports:
      - "1880:1880"

