version: "3.9"
services:
  grafana:
    image: "grafana/grafana"
    ports:
      - "8080:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel
    networks:
      - iot
  influxdb:
    image: "influxdb"
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - iot
  nodered:
    build:
      context: ./node-red
      dockerfile: Dockerfile
      args:
        node_red_version: "latest"
        node_red_contrib_ttn_version: "latest"
#        node_red_install_modules: ""
    user: "root"
    ports:
      - "8081:1880"
    depends_on:
      - influxdb
#    volumes:
#      - nodered-storage:/data
    environment:
      - NODE_RED_CREDENTIAL_SECRET=supadupasecret
      - TZ=Europe/Amsterdam
    networks:
      - iot
  mqtt:
    image: "eclipse-mosquitto"
    ports:
      - "8090:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-storage:/mosquitto/data
    networks:
      - iot
  dsmr:
    image: python:3
    build: dsmr
    environment:
      - MQTT_BROKER=mqtt
      - MQTT_CLIENT_NAME=dsmr
#      - MQTT_USER=admin
#      - MQTT_PASSWORD=admin
    depends_on:
      - mqtt
      - nodered
    networks:
      - iot
volumes:
  influxdb-storage:
  grafana-storage:
  nodered-storage:
  mqtt-storage:

networks:
  iot:
